#%RAML 1.0 Trait
description: ClientId Enforcement Trait
headers:
  client_id:
    example: 2nz7imk4ybjpor80hst1qaugcwld5v9x
    description: The Client ID is required to authenticate the requestor.
    type: string
  client_secret:
    example: dx4ouq3tengs80pjb976clvhyafw2mzi
    description: The Client Secret is required to authenticate the requestor.
    type: string