#%RAML 1.0 DataType
type: object
properties:
  firstname:
      type: string
      required: true
      description: First name
      example: "John"
  lastname:
      type: string
      required: true
      description: Last name
      example: "Smith"
  id:
      type: string
      required: true
      description: Id
      example: "1234"
  address:
      type: string
      required: false
      description: Address
      example: "4775 Whispering Pines Circle, Dallas, TX 75240"